version: "3.3"
services:
  runner:
    build: ./runner
    container_name: my_runner
    stdin_open: true
    tty: true
    volumes:
      - ./runner/src:/usr/src
    links:
      - "database:db"

  database:
    image: mongo:4.4
    container_name: my_database
    ports:
      - 69:27017
    volumes:
      - ./database/data/db:/data/db
    command: ["--bind_ip_all"]
