version: "3.8"
services:
  runner:
    build: ./runner
    stdin_open: true
    tty: true
    volumes:
      - ./runner/src:/usr/src
    links:
      - "database:db"

  database:
    image: mongo:4.4
    ports:
      - 69:27017
    volumes:
      - ./database/data/db:/data/db
