version: "3.3"
services:
  runner:
    build: ./runner
    container_name: my_runner
    stdin_open: true
    tty: true
    volumes:
      - ./runner/src:/usr/src
    links:
      - "database:db"

  database:
    image: mongo:4.4
    container_name: my_database
    ports:
      - 69:27017
    networks:
      mongo_net:
        ipv4_address: 172.16.0.1
    volumes:
      - ./database/data/db:/data/db
    command: mongod --bind_ip 127.0.0.1,172.16.0.1

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.254
