version: "3.3"
services:
  runner:
    build: ./runner
    container_name: my_runner
    stdin_open: true
    tty: true
    volumes:
      - ./runner/src:/usr/src
    networks:
      mongo_net:
        ipv4_address: 172.16.0.3
    links:
      - "database:db"

  database:
    build: ./database
    container_name: my_database
    ports:
      - 69:27017
    networks:
      mongo_net:
        ipv4_address: 172.16.0.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./database/data/db:/data/db
    command: ./startup.sh

networks:
  mongo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
