version: '3'
services:
  mongo:
    image: mongo:4.4
    container_name: finlab_mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: 'mongod --auth'
